language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements.redis.txt
  - pip install .
script:
  - python tests/test_datastores.py
